name: Test

on: [push, pull_request]

jobs:
    bazel-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/cache@v3
              with:
                  path: ~/.cache/bazelisk
                  key: ${{ runner.os }}--${{ hashFiles('**/.bazelversion') }}
            - uses: bazelbuild/setup-bazelisk@v2
            - run: bazel test --test_output=streamed //:all

    go-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: go build
            - run: ./ssh-agent-switcher -h 2>&1 | grep 'Usage of'
